//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appoitment
    {
        public int Id { get; set; }
        public System.DateTime Day { get; set; }
        public System.DateTime S_time { get; set; }
        public System.DateTime E_time { get; set; }
        public int petaint_id { get; set; }
    
        public virtual Petient Petient { get; set; }
        public Appoitment() { }
        public Appoitment(DateTime day, DateTime stime, DateTime entime)
        {
            this.Day = day;
            this.S_time = stime;
            this.E_time = entime;

        }
    }
}
