//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chech_Up
    {
        public int Id { get; set; }
        public string type { get; set; }
        public string Result { get; set; }
        public string diagnosis { get; set; }
        public Nullable<int> petiant_Id { get; set; }
        public string Examination_FName { get; set; }
        public string Ex_FExtention { get; set; }
        public string Ex_FContent { get; set; }
    
        public virtual Petient Petient { get; set; }
        public Chech_Up() { }
        public Chech_Up(string type, string resulte, string diag)
        {
            this.type = type;
            this.Result = resulte;
            this.diagnosis = diag;
        }
    }
}
