//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public int Id { get; set; }
        public string name { get; set; }
        public decimal dose { get; set; }
        public string period { get; set; }
        public string description { get; set; }
        public int petiant_id { get; set; }
        public string Examination_Fname { get; set; }
        public string Ex_extention { get; set; }
        public string Ex_Fcontent { get; set; }
    
        public virtual Petient Petient { get; set; }

        public Medication() { }
        public Medication(string name, decimal dose, string period, string desc)
        {
            this.name = name;
            this.dose = dose;
            this.period = period;
            this.description = desc;

        }
    }
}
