//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Petient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Petient()
        {
            this.Appoitments = new HashSet<Appoitment>();
            this.Chech_Up = new HashSet<Chech_Up>();
            this.Medications = new HashSet<Medication>();
            this.Reports = new HashSet<Report>();
        }
    
        public int Id { get; set; }
        public string F_name { get; set; }
        public string L_name { get; set; }
        public int age { get; set; }
        public string sex { get; set; }
        public int Doc_id { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public System.DateTime Date { get; set; }
        public bool active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appoitment> Appoitments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chech_Up> Chech_Up { get; set; }
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medication> Medications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }

        public Petient(string fname, string lname, int age, string sex, string phone, string email, DateTime date)
        {
            this.F_name = fname;
            this.L_name = lname;
            this.age = age;
            this.sex = sex;
            this.phone = phone;
            this.email = email;
            this.Date = date;
            this.Doc_id = 1;
            //this.Medications.Add(m1);
            //this.Appoitments.Add(appo1);
            //this.Chech_Up.Add(ch1);

        }
    }
}
